services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --host 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - jekyll-bundle-cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll-bundle-cache: